### ISSUE TITLE
Second Y-Axis

### ISSUE THREAD

**Issue by Tesch1988** [Aachen-3A/PlotLib#1]
Include the possibility to add a second y-Axis, for example eventnumbers on the left axis and efficiencies on the right axis. The default should be one axis.

**Comment by padeken** [comment]
So thomas wie schauts denn jetzt aus wann machst du das?

**Comment by Tesch1988** [comment]
Nicht vor Freitag!

**Comment by padeken** [comment]
Ok wir gucken montag nach

**Comment by Tesch1988** [comment]
The functionality is now included by adding a new list of histograms called hist_axis (default = [])
