### ISSUE TITLE
clean up needed 

### ISSUE THREAD

**Issue by padeken** [Aachen-3A/PlotLib#24]
The different plotting "kinds" self._Style_cont.Get_kind()
have much common code that does not need to be duplicate!
easier to read if one common bock!

**Comment by serdweg** [comment]
You want a clean up, you get a clean up.
I have deleted basically all which is no longer necessary in the draw_main function. Optimized the code structure that the code doubling is removed and removed the draw_axis function (without loosing its functionallity). There are now 130 lines code less.

**Comment by padeken** [comment]
you are the man!!
