### ISSUE TITLE
Add the possibility to plot 2D histograms

### ISSUE THREAD

**Issue by serdweg** [Aachen-3A/PlotLib#9]
To use a common style for 1D and 2D histogram plots, they also should be included in this library.

**Comment by Tesch1988** [comment]
The functionality is now included by adding a new list of histograms called hist_axis (default = [])

**Comment by serdweg** [comment]
Somebody has closed the wrong issue...

**Comment by serdweg** [comment]
The basic functionallity is now included, especially some style issues need to be improved
